language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - update-2
    - /^greenkeeper/.*$/
node_js:
  - '7'
  - '6'
script:
  - yarn start validate
  - yarn build
after_success:
  - yarn start reportCoverage
  - yarn start bithound
  - yarn start release
