language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - npm run test:coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release

