// flow-typed signature: bf54f2e177a294267a5b59a80e0c4932
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-destructuring_v~6.23.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-destructuring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-destructuring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-destructuring/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-destructuring/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-destructuring/lib/index'>;
}
