// flow-typed signature: 0d28d6773b8ee5fe8bf8e5c636196931
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-shorthand-properties_v~6.24.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-shorthand-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-shorthand-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-shorthand-properties/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-shorthand-properties/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-shorthand-properties/lib/index'>;
}
