// flow-typed signature: 24b208e61977c88ff11be9b151285dea
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-for-of_v~6.23.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-for-of'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-for-of' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-for-of/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-for-of/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-for-of/lib/index'>;
}
