// flow-typed signature: 7267721abff1ccd215ffb4e99e3f893a
// flow-typed version: <<STUB>>/rollup-plugin-cleanup_v~1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-cleanup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-cleanup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/blank-block' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/cleanup' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/parse-options' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/postproc' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/preproc' {
  declare module.exports: any;
}

declare module 'rollup-plugin-cleanup/src/util/filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.es.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.es'>;
}
declare module 'rollup-plugin-cleanup/dist/rollup-plugin-cleanup.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/dist/rollup-plugin-cleanup'>;
}
declare module 'rollup-plugin-cleanup/src/blank-block.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/blank-block'>;
}
declare module 'rollup-plugin-cleanup/src/cleanup.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/cleanup'>;
}
declare module 'rollup-plugin-cleanup/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/index'>;
}
declare module 'rollup-plugin-cleanup/src/parse-options.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/parse-options'>;
}
declare module 'rollup-plugin-cleanup/src/postproc.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/postproc'>;
}
declare module 'rollup-plugin-cleanup/src/preproc.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/preproc'>;
}
declare module 'rollup-plugin-cleanup/src/util/filter.js' {
  declare module.exports: $Exports<'rollup-plugin-cleanup/src/util/filter'>;
}
