// flow-typed signature: 656bc0482dc5eeb1976a1500bc8c13c3
// flow-typed version: <<STUB>>/rollup-plugin-conditional_v~1.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-conditional'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-conditional' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-conditional/build/rollup-plugin-conditional.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/build/rollup-plugin-conditional' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/rollup.config' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/src/plugin-api' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/test/fixtures/samplePlugins' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/test/fixtures/sourcecode' {
  declare module.exports: any;
}

declare module 'rollup-plugin-conditional/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-conditional/build/rollup-plugin-conditional.es.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/build/rollup-plugin-conditional.es'>;
}
declare module 'rollup-plugin-conditional/build/rollup-plugin-conditional.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/build/rollup-plugin-conditional'>;
}
declare module 'rollup-plugin-conditional/rollup.config.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/rollup.config'>;
}
declare module 'rollup-plugin-conditional/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/src/index'>;
}
declare module 'rollup-plugin-conditional/src/plugin-api.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/src/plugin-api'>;
}
declare module 'rollup-plugin-conditional/test/fixtures/samplePlugins.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/test/fixtures/samplePlugins'>;
}
declare module 'rollup-plugin-conditional/test/fixtures/sourcecode.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/test/fixtures/sourcecode'>;
}
declare module 'rollup-plugin-conditional/test/index.js' {
  declare module.exports: $Exports<'rollup-plugin-conditional/test/index'>;
}
