// flow-typed signature: e9db9f85552e5abf87c2ebfc5e2d023e
// flow-typed version: <<STUB>>/rollup-plugin-multi-dest_v~1.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-multi-dest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-multi-dest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-multi-dest/index' {
  declare module.exports: $Exports<'rollup-plugin-multi-dest'>;
}
declare module 'rollup-plugin-multi-dest/index.js' {
  declare module.exports: $Exports<'rollup-plugin-multi-dest'>;
}
