// flow-typed signature: 09ed9396fb8377a4f1740f85d261345e
// flow-typed version: <<STUB>>/rollup-plugin-gzip_v~1.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-gzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-gzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-gzip/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-gzip/lib/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-gzip/lib/index.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-gzip/lib/index.cjs'>;
}
declare module 'rollup-plugin-gzip/lib/index.es.js' {
  declare module.exports: $Exports<'rollup-plugin-gzip/lib/index.es'>;
}
