// flow-typed signature: 75d7a23c32d3357531b8548aa58447fd
// flow-typed version: <<STUB>>/rollup-plugin-uglify_v~1.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-uglify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-uglify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-uglify/dist/rollup-plugin-uglify.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-uglify/dist/rollup-plugin-uglify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-uglify/dist/rollup-plugin-uglify.es.js' {
  declare module.exports: $Exports<'rollup-plugin-uglify/dist/rollup-plugin-uglify.es'>;
}
declare module 'rollup-plugin-uglify/dist/rollup-plugin-uglify.js' {
  declare module.exports: $Exports<'rollup-plugin-uglify/dist/rollup-plugin-uglify'>;
}
